/*
 * bgr.c
 * Effect      : bgr
 * Description : swap color channels to BGR
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -color-matrix "0 0 1 0 1 0 1 0 0" <output>
 *
 * Style reference: ImageMagick -color-matrix
 */

#include <stddef.h>

/* ImageMagick option string (comma-separated so it stays a single arg) */
const char *const mediaeffects_bgr_magick = "-color-matrix 0,0,1,0,1,0,1,0,0";
