/*
 * derain.c
 * Effect      : derain
 * Description : fake derain color trick
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -colorspace srgb -set colorspace rgb -colorspace hsv -set colorspace rgb <output>
 *
 * Style reference: ImageMagick -colorspace, -set colorspace
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_derain_magick = "-colorspace srgb -set colorspace rgb -colorspace hsv -set colorspace rgb";
