/*
 * explode.c
 * Effect      : explode
 * Strength    : 2
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -implode -2.0000 <output>
 *
 * Style reference: ImageMagick -implode (negative = explode)
 */

#include <stddef.h>

/* ImageMagick option string (strength is negated for explode) */
const char *const mediaeffects_explode_magick = "-implode -2.0000";
