/*
 * fisheye.c
 * Effect      : fisheye
 * Strength    : 0.3
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   ffmpeg -i <input> -vf format=yuv444p16le,"geq='...'",scale=iw:ih,format=yuv420p <output>
 *
 * Style reference: ffmpeg geq filter (libavfilter/vf_geq.c)
 */

#include <stddef.h>

/* ffmpeg filter string; samples source pixels via p(x,y) */
const char *const mediaeffects_fisheye_vf =
    "format=yuv444p16le,"
    "geq='p(W*0.5+(X-W*0.5)*max(1-(0.3)*gauss(-3.3333*pow(hypot((X-W*0.5)/(W*0.5),(Y-H*0.5)/(H*0.5)),2)),0),"
    "H*0.5+(Y-H*0.5)*max(1-(0.3)*gauss(-3.3333*pow(hypot((X-W*0.5)/(W*0.5),(Y-H*0.5)/(H*0.5)),2)),0))',"
    "scale=iw:ih,format=yuv420p";
