/*
 * haah.c
 * Effect      : haah
 * Description : mirror left half onto the right
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -crop 50%x100%+0+0 +repage ( +clone -flop ) +append <output>
 *
 * Style reference: ImageMagick -crop, +clone, -flop, +append
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_haah_magick = "-crop 50%x100%+0+0 +repage ( +clone -flop ) +append";
