/*
 * hflip.c
 * Effect      : hflip
 * Description : mirror horizontally
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   ffmpeg -i <input> -vf hflip <output>
 *
 * Style reference: ffmpeg hflip filter (libavfilter/vf_hflip.c)
 */

#include <stddef.h>

/* ffmpeg filter string equivalent to: -vf hflip */
const char *const mediaeffects_hflip_vf = "hflip";
