/*
 * hooh.c
 * Effect      : hooh
 * Description : rotate 90, mirror half, rotate back
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -rotate 90 -crop 50%x100%+0+0 +repage ( +clone -flop ) +append -rotate -90 <output>
 *
 * Style reference: ImageMagick -rotate, -crop, +clone, -flop, +append
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_hooh_magick = "-rotate 90 -crop 50%x100%+0+0 +repage ( +clone -flop ) +append -rotate -90";
