/*
 * hsv.c
 * Effect      : hsv
 * Hue         : 180.0000 deg shift (no change: 0)
 * Saturation  : 0.0000 shift (no change: 0)
 * Value       : 0.0000 shift (no change: 0)
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -modulate 100,100,200 <output>
 *
 * Style reference: ImageMagick -modulate brightness,saturation,hue
 */

#include <stddef.h>

/* ImageMagick option string (brightness,saturation,hue percent) */
const char *const mediaeffects_hsv_magick = "-modulate 100,100,200";
