/*
 * hue.c
 * Effect      : hue
 * Angle       : 100.0000 degrees
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -colorspace yuv -fx "angle=100.0000*pi/180; channel(u,.5+(u.g-.5)*cos(angle)-(u.b-.5)*sin(angle),.5+(u.g-.5)*sin(angle)+(u.b-.5)*cos(angle))" -colorspace srgb <output>
 *
 * Style reference: ImageMagick -colorspace, -fx channel rotation
 */

#include <stddef.h>

/* ImageMagick option string (rotate UV chroma around luma) */
const char *const mediaeffects_hue_magick =
    "-colorspace yuv -fx \"angle=100.0000*pi/180; channel(u,.5+(u.g-.5)*cos(angle)-(u.b-.5)*sin(angle),.5+(u.g-.5)*sin(angle)+(u.b-.5)*cos(angle))\" -colorspace srgb";
