/*
 * invertlum.c
 * Effect      : invertlum
 * Description : invert luminosity in LAB colorspace
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -colorspace lab -channel r -negate +colorspace <output>
 *
 * Style reference: ImageMagick -colorspace, -channel, -negate
 */

#include <stddef.h>

/* ImageMagick option string (negate the L channel of LAB) */
const char *const mediaeffects_invertlum_magick = "-colorspace lab -channel r -negate +colorspace";
