/*
 * invert.c
 * Effect      : invert
 * Description : negate colors
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   ffmpeg -i <input> -vf negate <output>
 *
 * Style reference: ffmpeg negate filter (libavfilter/vf_negate.c)
 */

#include <stddef.h>

/* ffmpeg filter string equivalent to: -vf negate */
const char *const mediaeffects_invert_vf = "negate";

/* pixel-level operation: out = max - in */
static unsigned int mediaeffects_invert_pixel(unsigned int v, unsigned int max)
{
    return max - v;
}
