/*
 * magik.c
 * Effect      : magik
 * Description : liquid rescale to 50% x 50%, then resize 200%
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -liquid-rescale 50%x50% -resize 200% <output>
 *
 * Style reference: ImageMagick -liquid-rescale, -resize
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_magik_magick = "-liquid-rescale 50%x50% -resize 200%";
