/*
 * rain.c
 * Effect      : rain
 * Description : fake rain color trick
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -colorspace srgb -set colorspace hsv -colorspace scrgb -set colorspace srgb <output>
 *
 * Style reference: ImageMagick -colorspace, -set colorspace
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_rain_magick = "-colorspace srgb -set colorspace hsv -colorspace scrgb -set colorspace srgb";
