/*
 * resize.c
 * Effect      : resize
 * Size        : 50%
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -resize 50% <output>
 *
 * Style reference: ImageMagick -resize
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_resize_magick = "-resize 50%";
