/*
 * rotate.c
 * Effect      : rotate
 * Angle       : 45 degrees (counter-clockwise)
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   ffmpeg -i <input> -vf rotate=45*3.141592653589793/180 <output>
 *
 * Style reference: ffmpeg rotate filter (libavfilter/vf_rotate.c)
 *
 * Note: ffmpeg rotate takes radians; degrees are converted as deg*PI/180.
 */

#include <stddef.h>

/* ffmpeg filter string (angle in radians) */
const char *const mediaeffects_rotate_vf = "rotate=45*3.141592653589793/180";
