/*
 * stretch.c
 * Effect      : stretch
 * Description : stretch/squeeze horizontally and vertically
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   ffmpeg -i <input> -vf format=yuv444p,rotate=0:iw*1.1:ih*1.1,"geq='p((W/2)+(X-(W/2))/<x>,(H/2)+(Y-(H/2))/<y>)'",scale=iw:ih,crop=<w>:<h>,format=yuv420p <output>
 *
 * Style reference: ffmpeg geq filter
 */

#include <stddef.h>

/* ffmpeg filter string (x,y scale factors; crop to original <w>x<h>) */
const char *const mediaeffects_stretch_vf =
    "format=yuv444p,rotate=0:iw*1.1:ih*1.1,"
    "geq='p((W/2)+(X-(W/2))/<x>,(H/2)+(Y-(H/2))/<y>)',scale=iw:ih,crop=<w>:<h>,format=yuv420p";
