/*
 * swirl.c
 * Effect      : swirl
 * Strength    : 30 degrees
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -swirl 30 <output>
 *
 * Style reference: ImageMagick -swirl
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_swirl_magick = "-swirl 30";
