/*
 * vflip.c
 * Effect      : vflip
 * Description : mirror vertically
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   ffmpeg -i <input> -vf vflip <output>
 *
 * Style reference: ffmpeg vflip filter (libavfilter/vf_vflip.c)
 */

#include <stddef.h>

/* ffmpeg filter string equivalent to: -vf vflip */
const char *const mediaeffects_vflip_vf = "vflip";
