/*
 * waaw.c
 * Effect      : waaw
 * Description : flop, then mirror left half onto the right
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -flop -crop 50%x100%+0+0 +repage ( +clone -flop ) +append <output>
 *
 * Style reference: ImageMagick -flop, -crop, +clone, -flop, +append
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_waaw_magick = "-flop -crop 50%x100%+0+0 +repage ( +clone -flop ) +append";
