/*
 * wave.c
 * Effect      : wave
 * Params      : 3.2000,3.2000,0.0500,0.0500,0.6280,0.6280,0.0000,0.0000
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   ffmpeg -i <input> -vf format=yuv444p,scale=640:640,"geq='p(X-((sin((T*5*<xs>+(<xp>))+(Y/H)*(PI*<xf>)))*(-<xa>*600)),Y-((sin((T*5*<ys>+(<yp>))+(X/W)*(PI*<yf>)))*(-<ya>*600)))'",scale=<w>:<h>,format=yuv420p <output>
 *
 * Style reference: ffmpeg geq filter
 */

#include <stddef.h>

/* ffmpeg filter string (xfreq,yfreq,xamp,yamp,xphase,yphase,xspeed,yspeed) */
const char *const mediaeffects_wave_vf =
    "format=yuv444p,scale=640:640,"
    "geq='p(X-((sin((T*5*<xs>+(<xp>))+(Y/H)*(PI*<xf>)))*(-<xa>*600)),"
    "Y-((sin((T*5*<ys>+(<yp>))+(X/W)*(PI*<yf>)))*(-<ya>*600)))',"
    "scale=<w>:<h>,format=yuv420p";
