/*
 * woow.c
 * Effect      : woow
 * Description : rotate 90 + flop, mirror half, rotate back
 * Generated by: mediaeffects
 *
 * CLI equivalent:
 *   magick <input> -rotate 90 -flop -crop 50%x100%+0+0 +repage ( +clone -flop ) +append -rotate -90 <output>
 *
 * Style reference: ImageMagick -rotate, -flop, -crop, +clone, -flop, +append
 */

#include <stddef.h>

/* ImageMagick option string */
const char *const mediaeffects_woow_magick = "-rotate 90 -flop -crop 50%x100%+0+0 +repage ( +clone -flop ) +append -rotate -90";
